Repository NewEraTeam/NewEraProject, pull requests merged in 2024-12, with the labels that each got.

#11 Include View Profile Module
  NewEra/resources/views/MainPageModule/MainPage.blade.php
  NewEra/resources/views/ViewProfileModule/ViewProfile.blade.php
  NewEra/routes/web.php
Labels: bug, help wanted

#12 Completed Customer Booking Page
  NewEra/resources/views/CustomerBookingModule/CustomerBooking.blade.php
  NewEra/resources/views/MainPageModule/MainPage.blade.php
  NewEra/routes/web.php
Labels: documentation, enhancement

#15 Language Module Translation
  NewEra/app/Http/Controllers/LocalizationController.php
  NewEra/app/Http/Kernel.php
  NewEra/app/Http/Middleware/LocalizationMiddleware.php
  NewEra/app/Providers/AppServiceProvider.php
  NewEra/lang/en/auth.php
  NewEra/lang/en/pagination.php
  NewEra/lang/en/passwords.php
  NewEra/lang/en/validation.php
  NewEra/public/js/languageDropdown.js
  NewEra/resources/views/CustomerBookingModule/CustomerBooking.blade.php
  NewEra/resources/views/LanguageTranslationModule/bm.php
  NewEra/resources/views/LanguageTranslationModule/cn.php
  NewEra/resources/views/LanguageTranslationModule/en.php
  NewEra/resources/views/MainPageModule/MainPage.blade.php
  NewEra/routes/web.php
Labels: bug, help wanted

#16 View profile blade update
  NewEra/resources/views/ViewProfileModule/ViewProfile.blade.php
Labels: enhancement

#34 Update abous us
  NewEra/app/Http/Controllers/ProfileController.php
  NewEra/public/UTM Campus.png
  NewEra/resources/views/AboutUsModule/AboutUs.blade.php
  NewEra/resources/views/ViewProfileModule/ViewProfile.blade.php
  NewEra/routes/web.php
Labels: enhancement

#31 Establish Connection to Admin Page
  NewEra/app/Http/Controllers/AdminController.php
  NewEra/app/Http/Kernel.php
  NewEra/app/Models/UserData.php
  NewEra/config/auth.php
  NewEra/resources/views/AdminModule/AdminMainPageModule/AdminMain.blade.php
  NewEra/resources/views/CustomerModule/CustomerBooking.blade.php
  NewEra/resources/views/MainPageModule/MainPage.blade.php
  NewEra/routes/web.php
Labels: bug, help wanted

#37 Minor Changes
  NewEra/resources/views/AboutUsModule/AboutUs.blade.php
  NewEra/resources/views/CustomerBookingModule/CustomerBooking.blade.php
  NewEra/resources/views/MainPageModule/MainPage.blade.php
  NewEra/resources/views/ViewProfileModule/ViewProfile.blade.php
  NewEra/routes/web.php
Labels: enhancement

#40 UTM logo main page redirect
  NewEra/resources/views/AboutUsModule/AboutUs.blade.php
  NewEra/resources/views/CustomerBookingModule/CustomerBooking.blade.php
  NewEra/resources/views/MainPageModule/MainPage.blade.php
  NewEra/resources/views/ViewProfileModule/ViewProfile.blade.php
Labels: enhancement
