Repository NewEraTeam/NewEraProject, pull requests merged in 2025-01, with the labels that each got.

#47 Add Page for Admin Manage Faciltiy
  NewEra/resources/views/AdminModule/AdminManageFacilitiesModule/AdminManageFacilities.blade.php
  NewEra/routes/web.php
Labels: bug, enhancement

#52 Picture route
  NewEra/resources/views/FacilityModules/badminton.blade.php
  NewEra/resources/views/FacilityModules/gym.blade.php
  NewEra/resources/views/FacilityModules/stadium.blade.php
  NewEra/resources/views/FacilityModules/swimming.blade.php
Labels: enhancement

#58 changes to profile
  NewEra/app/Http/Controllers/UserController.php
  NewEra/app/Http/Controllers/ViewProfileController.php
  NewEra/resources/views/ViewProfileModule/ViewProfile.blade.php
  NewEra/routes/web.php
Labels: bug
